from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        alter table adminrole modify roleid bigint not null after id;
alter table adminrole drop foreign key adminrole_ibfk_1;
drop index adminrole_guild_id on adminrole;
alter table adminrole charset = utf8mb4;
create index idx_adminrole_guild_i_1576b8 on adminrole (guild_id);
alter table adminrole add constraint uid_adminrole_roleid_457f6b unique (roleid, guild_id);
alter table adminrole add constraint fk_adminrol_guild_56368cba foreign key (guild_id) references guild (id) on delete cascade;
create table aerich (id int auto_increment primary key, version varchar(255) not null, app varchar(100) not null, content json not null);
alter table artchannel alter column listenchannelid set default 0;
alter table artchannel alter column collectionchannelid set default 0;
alter table artchannel modify tag varchar(50) default '' not null;
alter table artchannel charset = utf8mb4;
alter table artchannel add constraint uid_artchannel_serveri_dacf81 unique (serverid, listenchannelid, collectionchannelid, tag);
alter table autoresponder modify `trigger` varchar(300) not null;
alter table autoresponder modify response varchar(2000) not null;
alter table autoresponder alter column flags set default 0;
alter table autoresponder alter column chance set default 10000;
alter table autoresponder alter column responsechannelid set default 0;
alter table autoresponder alter column listenchannelid set default 0;
alter table autoresponder alter column logchannelid set default 0;
alter table autoresponder charset = utf8mb4;
alter table autoresponder add constraint uid_autorespond_trigger_d7d834 unique (`trigger`, serverid);
alter table botadmin charset = utf8mb4;
alter table botadmin add constraint userid unique (userid);
alter table configchannel modify serverid bigint not null after id;
alter table configchannel modify configname varchar(100) not null;
alter table configchannel alter column channelid set default 0;
alter table configchannel charset = utf8mb4;
alter table configchannel add constraint uid_configchann_confign_21c1ab unique (configname, serverid);
alter table countword modify word varchar(300) not null;
alter table countword charset = utf8mb4;
alter table countword add constraint uid_countword_word_931444 unique (word, serverid);
alter table customcommand modify `trigger` varchar(20) not null;
alter table customcommand modify response varchar(2000) not null;
alter table customcommand alter column deletetrigger set default 0;
alter table customcommand alter column reply set default 0;
alter table customcommand charset = utf8mb4;
alter table customcommand add constraint uid_customcomma_trigger_65c25c unique (`trigger`, serverid);
alter table dropboxchannel alter column targetchannelid set default 0;
alter table dropboxchannel alter column deletedelayms set default 0;
alter table dropboxchannel charset = utf8mb4;
alter table dropboxchannel add sendreceipt tinyint(1) default 0 not null;
alter table dropboxchannel add constraint uid_dropboxchan_serveri_7254d9 unique (serverid, sourcechannelid);
alter table guild alter column memberrole set default 0;
alter table guild alter column nonmemberrole set default 0;
alter table guild alter column mutedrole set default 0;
alter table guild alter column welcomechannelid set default 0;
alter table guild alter column ruleschannelid set default 0;
alter table guild alter column logchannelid set default 0;
alter table guild alter column entrychannelid set default 0;
alter table guild alter column rulesreactmessageid set default 0;
alter table guild charset = utf8mb4;
alter table guild add constraint serverid unique (serverid);
alter table localization alter column channelid set default 0;
alter table localization alter column locale set default '';
alter table localization modify guild_id int not null after locale;
alter table localization drop foreign key localization_ibfk_1;
drop index localization_guild_id on localization;
alter table localization charset = utf8mb4;
create index idx_localizatio_guild_i_2a3780 on localization (guild_id);
alter table localization add constraint uid_localizatio_guild_i_1e041d unique (guild_id, channelid);
alter table localization add constraint fk_localiza_guild_9f755aae foreign key (guild_id) references guild (id) on delete cascade;
alter table modrole modify roleid bigint not null after id;
alter table modrole drop foreign key modrole_ibfk_1;
drop index modrole_guild_id on modrole;
alter table modrole charset = utf8mb4;
create index idx_modrole_guild_i_cc7b59 on modrole (guild_id);
alter table modrole add constraint uid_modrole_roleid_b1b1c0 unique (roleid, guild_id);
alter table modrole add constraint fk_modrole_guild_62488d68 foreign key (guild_id) references guild (id) on delete cascade;
alter table premiumtier modify roleid bigint not null after id;
alter table premiumtier drop key premiumtier_roleid;
alter table premiumtier drop foreign key premiumtier_ibfk_1;
drop index premiumtier_guild_id on premiumtier;
alter table premiumtier charset = utf8mb4;
create index idx_premiumtier_guild_i_fccc23 on premiumtier (guild_id);
alter table premiumtier add constraint uid_premiumtier_guild_i_a70ac3 unique (guild_id, roleid);
alter table premiumtier add constraint fk_premiumt_guild_837e09ee foreign key (guild_id) references guild (id) on delete cascade;
alter table premiumtiermember drop foreign key premiumtiermember_ibfk_1;
drop index premiumtiermember_tier_id on premiumtiermember;
alter table premiumtiermember charset = utf8mb4;
alter table premiumtiermember add constraint fk_premiumt_premiumt_88d18cb9 foreign key (tier_id) references premiumtier (id) on delete cascade;
alter table premiumtiermemberinfo modify value varchar(500) not null after requirementid;
alter table premiumtiermemberinfo drop foreign key premiumtiermemberinfo_ibfk_1;
drop index premiumtiermemberinfo_member_id on premiumtiermemberinfo;
alter table premiumtiermemberinfo charset = utf8mb4;
alter table premiumtiermemberinfo add constraint fk_premiumt_premiumt_b72570c3 foreign key (member_id) references premiumtiermember (id) on delete cascade;
alter table premiumtierrequirement modify name varchar(100) not null;
alter table premiumtierrequirement modify prompt varchar(500) not null;
alter table premiumtierrequirement modify tier_id int not null after prompt;
alter table premiumtierrequirement drop foreign key premiumtierrequirement_ibfk_1;
drop index premiumtierrequirement_tier_id on premiumtierrequirement;
alter table premiumtierrequirement charset = utf8mb4;
alter table premiumtierrequirement add constraint fk_premiumt_premiumt_cff8c276 foreign key (tier_id) references premiumtier (id) on delete cascade;
alter table reactwatch modify muteduration smallint default 600 not null after serverid;
alter table reactwatch alter column watchremoves set default 0;
alter table reactwatch charset = utf8mb4;
alter table reactwatch add constraint serverid unique (serverid);
alter table trustedrole modify roleid bigint not null after id;
alter table trustedrole drop foreign key trustedrole_ibfk_1;
drop index trustedrole_guild_id on trustedrole;
alter table trustedrole charset = utf8mb4;
create index idx_trustedrole_guild_i_deb2b1 on trustedrole (guild_id);
alter table trustedrole add constraint uid_trustedrole_roleid_215f34 unique (roleid, guild_id);
alter table trustedrole add constraint fk_trustedr_guild_7af9759e foreign key (guild_id) references guild (id) on delete cascade;
alter table userpermission alter column command set default '';
alter table userpermission alter column allow set default 1;
alter table userpermission modify guild_id int not null after allow;
alter table userpermission drop foreign key userpermission_ibfk_1;
drop index userpermission_guild_id on userpermission;
alter table userpermission charset = utf8mb4;
create index idx_userpermiss_guild_i_3a0dc1 on userpermission (guild_id);
alter table userpermission add constraint uid_userpermiss_userid_7b40ae unique (userid, command);
alter table userpermission add constraint fk_userperm_guild_24ce9edd foreign key (guild_id) references guild (id) on delete cascade;
alter table watchedemoji alter column log set default 0;
alter table watchedemoji alter column remove set default 0;
alter table watchedemoji alter column mute set default 0;
alter table watchedemoji modify watcher_id int not null after mute;
alter table watchedemoji drop foreign key watchedemoji_ibfk_1;
drop index watchedemoji_watcher_id on watchedemoji;
alter table watchedemoji charset = utf8mb4;
create index idx_watchedemoj_watcher_a04b30 on watchedemoji (watcher_id);
alter table watchedemoji add constraint uid_watchedemoj_emoji_4203dc unique (emoji, watcher_id);
alter table watchedemoji add constraint fk_watchede_reactwat_b8aaa411 foreign key (watcher_id) references reactwatch (id) on delete cascade;"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        ALTER TABLE `artchannel` MODIFY COLUMN `tag` VARCHAR(30) NOT NULL  DEFAULT '';"""
